drop table if exists schedule;

CREATE TABLE schedule (
      id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
      classroom VARCHAR(10) NOT NULL,
      time TIME NOT NULL,
      day_of_week varchar(10) NOT NULL,
      teacher VARCHAR(100) NOT NULL,
      group_name VARCHAR(50) NOT NULL
);